version: "3.9"

services:
  stockfish:
    build: ./stockfish
    container_name: stockfish_engine
    ports:
    - "3334:3334"

  analyzer:
    build: ./engine
    container_name: chess_analyzer
    environment:
        - LICHESS_USERNAME=${LICHESS_USERNAME}
    depends_on:
      - stockfish

  collector:
    build: ./collectors
    container_name: chess_collector
    environment:
        - LICHESS_USERNAME=${LICHESS_USERNAME}

  
  redis:
    image: redis:7-alpine
    restart: always

  celery:
    build: ./scheduler
    depends_on:
      - redis
      - stockfish
    environment:
      - LICHESS_USERNAME=${LICHESS_USERNAME}
    volumes:
      - ./data:/app/data          # shared data folder for both scripts
      - ./collector:/app/collector
      - ./analyzer:/app/analyzer