name: "Security Scan"

on: [push, pull_request]


jobs:
  sca_scan:
    name: Snyk (SCA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Snyk Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --all-projects --file-skip-checks=true